[program:los-chavos-worker]
process_name=%(program_name)s_%(process_num)02d
command=/opt/plesk/php/8.3/bin/php /var/www/vhosts/los-chavos.site/httpdocs/artisan queue:work --queue=default --tries=3 --max-time=3600 --sleep=3 --timeout=120
autostart=true
autorestart=true
user=los-chavos.site_sfdakxyn90k
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/vhosts/los-chavos.site/httpdocs/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600
stopsignal=QUIT